# seed_data.py
# Dữ liệu hệ thống tài khoản mặc định cho Finiip

DEFAULT_ACCOUNTS = [{'code': '001', 'name': 'Tài sản thuê ngoài', 'account_type': 'off_balance'},
 {'code': '002',
  'name': 'Vật tư, hàng hóa nhận giữ hộ, nhận gia công',
  'account_type': 'off_balance'},
 {'code': '003',
  'name': 'Hàng hóa nhận bán hộ, nhận ký gửi, ký cược',
  'account_type': 'off_balance'},
 {'code': '004', 'name': 'Nợ khó đòi đã xử lý', 'account_type': 'off_balance'},
 {'code': '007', 'name': 'Ngoại tệ các loại', 'account_type': 'off_balance'},
 {'code': '111', 'name': 'Tiền mặt', 'account_type': 'asset'},
 {'code': '1111', 'name': 'Tiền Việt Nam', 'account_type': 'asset'},
 {'code': '1112', 'name': 'Ngoại tệ', 'account_type': 'asset'},
 {'code': '1113', 'name': 'Vàng tiền tệ', 'account_type': 'asset'},
 {'code': '112', 'name': 'Tiền gửi ngân hàng', 'account_type': 'asset'},
 {'code': '1121', 'name': 'Tiền Việt Nam gửi ngân hàng', 'account_type': 'asset'},
 {'code': '1122', 'name': 'Ngoại tệ gửi ngân hàng', 'account_type': 'asset'},
 {'code': '1123', 'name': 'Vàng tiền tệ gửi ngân hàng', 'account_type': 'asset'},
 {'code': '113', 'name': 'Tiền đang chuyển', 'account_type': 'asset'},
 {'code': '1131', 'name': 'Tiền Việt Nam đang chuyển', 'account_type': 'asset'},
 {'code': '1132', 'name': 'Ngoại tệ đang chuyển', 'account_type': 'asset'},
 {'code': '121', 'name': 'Chứng khoán kinh doanh', 'account_type': 'asset'},
 {'code': '1211', 'name': 'Cổ phiếu', 'account_type': 'asset'},
 {'code': '1212', 'name': 'Trái phiếu', 'account_type': 'asset'},
 {'code': '1218', 'name': 'Chứng khoán và công cụ tài chính khác', 'account_type': 'asset'},
 {'code': '128', 'name': 'Đầu tư nắm giữ đến ngày đáo hạn', 'account_type': 'asset'},
 {'code': '1281', 'name': 'Tiền gửi có kỳ hạn', 'account_type': 'asset'},
 {'code': '1282', 'name': 'Trái phiếu', 'account_type': 'asset'},
 {'code': '1283', 'name': 'Cho vay', 'account_type': 'asset'},
 {'code': '1288',
  'name': 'Các khoản đầu tư khác nắm giữ đến ngày đáo hạn',
  'account_type': 'asset'},
 {'code': '131', 'name': 'Phải thu của khách hàng', 'account_type': 'asset'},
 {'code': '133', 'name': 'Thuế GTGT được khấu trừ', 'account_type': 'asset'},
 {'code': '1331', 'name': 'Thuế GTGT được khấu trừ của hàng hóa, dịch vụ', 'account_type': 'asset'},
 {'code': '1332', 'name': 'Thuế GTGT được khấu trừ của tài sản cố định', 'account_type': 'asset'},
 {'code': '136', 'name': 'Phải thu nội bộ', 'account_type': 'asset'},
 {'code': '1361', 'name': 'Vốn kinh doanh ở đơn vị trực thuộc', 'account_type': 'asset'},
 {'code': '1362', 'name': 'Phải thu nội bộ về chênh lệch tỷ giá', 'account_type': 'asset'},
 {'code': '1363',
  'name': 'Phải thu nội bộ về chi phí đi vay đủ điều kiện vốn hóa',
  'account_type': 'asset'},
 {'code': '1368', 'name': 'Phải thu nội bộ khác', 'account_type': 'asset'},
 {'code': '138', 'name': 'Phải thu khác', 'account_type': 'asset'},
 {'code': '1381', 'name': 'Tài sản thiếu chờ xử lý', 'account_type': 'asset'},
 {'code': '1385', 'name': 'Phải thu về cổ phần hóa', 'account_type': 'asset'},
 {'code': '1388', 'name': 'Phải thu khác', 'account_type': 'asset'},
 {'code': '141', 'name': 'Tạm ứng', 'account_type': 'asset'},
 {'code': '151', 'name': 'Hàng mua đang đi đường', 'account_type': 'asset'},
 {'code': '152', 'name': 'Nguyên liệu, vật liệu', 'account_type': 'asset'},
 {'code': '153', 'name': 'Công cụ, dụng cụ', 'account_type': 'asset'},
 {'code': '154', 'name': 'Chi phí sản xuất, kinh doanh dở dang', 'account_type': 'asset'},
 {'code': '155', 'name': 'Thành phẩm', 'account_type': 'asset'},
 {'code': '1551', 'name': 'Thành phẩm nhập kho', 'account_type': 'asset'},
 {'code': '1557', 'name': 'Thành phẩm bất động sản', 'account_type': 'asset'},
 {'code': '156', 'name': 'Hàng hóa', 'account_type': 'asset'},
 {'code': '1561', 'name': 'Giá mua hàng hóa', 'account_type': 'asset'},
 {'code': '1562', 'name': 'Chi phí thu mua hàng hóa', 'account_type': 'asset'},
 {'code': '1567', 'name': 'Hàng hóa bất động sản', 'account_type': 'asset'},
 {'code': '157', 'name': 'Hàng gửi đi bán', 'account_type': 'asset'},
 {'code': '158', 'name': 'Hàng hóa kho bảo thuế', 'account_type': 'asset'},
 {'code': '161', 'name': 'Chi sự nghiệp', 'account_type': 'asset'},
 {'code': '1611', 'name': 'Chi sự nghiệp năm trước', 'account_type': 'asset'},
 {'code': '1612', 'name': 'Chi sự nghiệp năm nay', 'account_type': 'asset'},
 {'code': '171', 'name': 'Giao dịch mua bán lại trái phiếu Chính phủ', 'account_type': 'asset'},
 {'code': '211', 'name': 'Tài sản cố định hữu hình', 'account_type': 'asset'},
 {'code': '2111', 'name': 'Nhà cửa, vật kiến trúc', 'account_type': 'asset'},
 {'code': '2112', 'name': 'Máy móc, thiết bị', 'account_type': 'asset'},
 {'code': '2113', 'name': 'Phương tiện vận tải, truyền dẫn', 'account_type': 'asset'},
 {'code': '2114', 'name': 'Thiết bị, dụng cụ quản lý', 'account_type': 'asset'},
 {'code': '2115', 'name': 'Cây lâu năm, súc vật làm việc và cho sản phẩm', 'account_type': 'asset'},
 {'code': '2118', 'name': 'Tài sản cố định hữu hình khác', 'account_type': 'asset'},
 {'code': '212', 'name': 'Tài sản cố định thuê tài chính', 'account_type': 'asset'},
 {'code': '2121', 'name': 'Tài sản cố định hữu hình thuê tài chính', 'account_type': 'asset'},
 {'code': '2122', 'name': 'Tài sản cố định vô hình thuê tài chính', 'account_type': 'asset'},
 {'code': '213', 'name': 'Tài sản cố định vô hình', 'account_type': 'asset'},
 {'code': '2131', 'name': 'Quyền sử dụng đất', 'account_type': 'asset'},
 {'code': '2132', 'name': 'Quyền phát hành', 'account_type': 'asset'},
 {'code': '2133', 'name': 'Bản quyền, bằng sáng chế', 'account_type': 'asset'},
 {'code': '2134', 'name': 'Nhãn hiệu, tên thương mại', 'account_type': 'asset'},
 {'code': '2135', 'name': 'Chương trình phần mềm', 'account_type': 'asset'},
 {'code': '2136', 'name': 'Giấy phép và giấy phép nhượng quyền', 'account_type': 'asset'},
 {'code': '2138', 'name': 'Tài sản cố định vô hình khác', 'account_type': 'asset'},
 {'code': '214', 'name': 'Hao mòn tài sản cố định', 'account_type': 'asset'},
 {'code': '2141', 'name': 'Hao mòn tài sản cố định hữu hình', 'account_type': 'asset'},
 {'code': '2142', 'name': 'Hao mòn tài sản cố định thuê tài chính', 'account_type': 'asset'},
 {'code': '2143', 'name': 'Hao mòn tài sản cố định vô hình', 'account_type': 'asset'},
 {'code': '2147', 'name': 'Hao mòn bất động sản đầu tư', 'account_type': 'asset'},
 {'code': '217', 'name': 'Bất động sản đầu tư', 'account_type': 'asset'},
 {'code': '221', 'name': 'Đầu tư vào công ty con', 'account_type': 'asset'},
 {'code': '222', 'name': 'Đầu tư vào công ty liên doanh, liên kết', 'account_type': 'asset'},
 {'code': '228', 'name': 'Đầu tư khác', 'account_type': 'asset'},
 {'code': '2281', 'name': 'Đầu tư góp vốn vào đơn vị khác', 'account_type': 'asset'},
 {'code': '2288', 'name': 'Đầu tư khác', 'account_type': 'asset'},
 {'code': '229', 'name': 'Dự phòng tổn thất tài sản', 'account_type': 'asset'},
 {'code': '2291', 'name': 'Dự phòng giảm giá chứng khoán kinh doanh', 'account_type': 'asset'},
 {'code': '2292', 'name': 'Dự phòng tổn thất đầu tư vào đơn vị khác', 'account_type': 'asset'},
 {'code': '2293', 'name': 'Dự phòng phải thu khó đòi', 'account_type': 'asset'},
 {'code': '2294', 'name': 'Dự phòng giảm giá hàng tồn kho', 'account_type': 'asset'},
 {'code': '241', 'name': 'Xây dựng cơ bản dở dang', 'account_type': 'asset'},
 {'code': '2411', 'name': 'Mua sắm tài sản cố định', 'account_type': 'asset'},
 {'code': '2412', 'name': 'Xây dựng cơ bản', 'account_type': 'asset'},
 {'code': '2413', 'name': 'Sửa chữa lớn tài sản cố định', 'account_type': 'asset'},
 {'code': '242', 'name': 'Chi phí trả trước', 'account_type': 'asset'},
 {'code': '243', 'name': 'Tài sản thuế thu nhập hoãn lại', 'account_type': 'asset'},
 {'code': '244', 'name': 'Cầm cố, thế chấp, ký quỹ, ký cược', 'account_type': 'asset'},
 {'code': '331', 'name': 'Phải trả cho người bán', 'account_type': 'liability'},
 {'code': '333', 'name': 'Thuế và các khoản phải nộp Nhà nước', 'account_type': 'liability'},
 {'code': '3331', 'name': 'Thuế GTGT phải nộp', 'account_type': 'liability'},
 {'code': '33311', 'name': 'Thuế GTGT đầu ra', 'account_type': 'liability'},
 {'code': '33312', 'name': 'Thuế GTGT hàng nhập khẩu', 'account_type': 'liability'},
 {'code': '3332', 'name': 'Thuế tiêu thụ đặc biệt', 'account_type': 'liability'},
 {'code': '3333', 'name': 'Thuế xuất, nhập khẩu', 'account_type': 'liability'},
 {'code': '3334', 'name': 'Thuế thu nhập doanh nghiệp', 'account_type': 'liability'},
 {'code': '3335', 'name': 'Thuế thu nhập cá nhân', 'account_type': 'liability'},
 {'code': '3336', 'name': 'Thuế tài nguyên', 'account_type': 'liability'},
 {'code': '3337', 'name': 'Thuế nhà đất, tiền thuê đất', 'account_type': 'liability'},
 {'code': '3338',
  'name': 'Thuế bảo vệ môi trường và các loại thuế khác',
  'account_type': 'liability'},
 {'code': '3339', 'name': 'Phí, lệ phí và các khoản phải nộp khác', 'account_type': 'liability'},
 {'code': '334', 'name': 'Phải trả người lao động', 'account_type': 'liability'},
 {'code': '3341', 'name': 'Phải trả công nhân viên', 'account_type': 'liability'},
 {'code': '3348', 'name': 'Phải trả người lao động khác', 'account_type': 'liability'},
 {'code': '335', 'name': 'Chi phí phải trả', 'account_type': 'liability'},
 {'code': '336', 'name': 'Phải trả nội bộ', 'account_type': 'liability'},
 {'code': '3361', 'name': 'Phải trả nội bộ về vốn kinh doanh', 'account_type': 'liability'},
 {'code': '3362', 'name': 'Phải trả nội bộ về chênh lệch tỷ giá', 'account_type': 'liability'},
 {'code': '3363',
  'name': 'Phải trả nội bộ về chi phí đi vay đủ điều kiện vốn hóa',
  'account_type': 'liability'},
 {'code': '3368', 'name': 'Phải trả nội bộ khác', 'account_type': 'liability'},
 {'code': '337',
  'name': 'Thanh toán theo tiến độ kế hoạch hợp đồng xây dựng',
  'account_type': 'liability'},
 {'code': '338', 'name': 'Phải trả, phải nộp khác', 'account_type': 'liability'},
 {'code': '3381', 'name': 'Tài sản thừa chờ giải quyết', 'account_type': 'liability'},
 {'code': '3382', 'name': 'Kinh phí công đoàn', 'account_type': 'liability'},
 {'code': '3383', 'name': 'Bảo hiểm xã hội', 'account_type': 'liability'},
 {'code': '3384', 'name': 'Bảo hiểm y tế', 'account_type': 'liability'},
 {'code': '3385', 'name': 'Phải trả về cổ phần hóa', 'account_type': 'liability'},
 {'code': '3386', 'name': 'Bảo hiểm thất nghiệp', 'account_type': 'liability'},
 {'code': '3387', 'name': 'Doanh thu chưa thực hiện', 'account_type': 'liability'},
 {'code': '3388', 'name': 'Phải trả, phải nộp khác', 'account_type': 'liability'},
 {'code': '341', 'name': 'Vay và nợ thuê tài chính', 'account_type': 'liability'},
 {'code': '3411', 'name': 'Các khoản đi vay', 'account_type': 'liability'},
 {'code': '3412', 'name': 'Nợ thuê tài chính', 'account_type': 'liability'},
 {'code': '343', 'name': 'Trái phiếu phát hành', 'account_type': 'liability'},
 {'code': '3431', 'name': 'Trái phiếu thường', 'account_type': 'liability'},
 {'code': '34311', 'name': 'Mệnh giá trái phiếu', 'account_type': 'liability'},
 {'code': '34312', 'name': 'Chiết khấu trái phiếu', 'account_type': 'liability'},
 {'code': '34313', 'name': 'Phụ trội trái phiếu', 'account_type': 'liability'},
 {'code': '3432', 'name': 'Trái phiếu chuyển đổi', 'account_type': 'liability'},
 {'code': '344', 'name': 'Nhận ký quỹ, ký cược', 'account_type': 'liability'},
 {'code': '347', 'name': 'Thuế thu nhập hoãn lại phải trả', 'account_type': 'liability'},
 {'code': '352', 'name': 'Dự phòng phải trả', 'account_type': 'liability'},
 {'code': '3521', 'name': 'Dự phòng bảo hành sản phẩm hàng hóa', 'account_type': 'liability'},
 {'code': '3522', 'name': 'Dự phòng bảo hành công trình xây dựng', 'account_type': 'liability'},
 {'code': '3523', 'name': 'Dự phòng tái cơ cấu doanh nghiệp', 'account_type': 'liability'},
 {'code': '3524', 'name': 'Dự phòng phải trả khác', 'account_type': 'liability'},
 {'code': '353', 'name': 'Quỹ khen thưởng, phúc lợi', 'account_type': 'liability'},
 {'code': '3531', 'name': 'Quỹ khen thưởng', 'account_type': 'liability'},
 {'code': '3532', 'name': 'Quỹ phúc lợi', 'account_type': 'liability'},
 {'code': '3533',
  'name': 'Quỹ phúc lợi đã hình thành tài sản cố định',
  'account_type': 'liability'},
 {'code': '3534', 'name': 'Quỹ thưởng ban quản lý điều hành công ty', 'account_type': 'liability'},
 {'code': '356', 'name': 'Quỹ phát triển khoa học và công nghệ', 'account_type': 'liability'},
 {'code': '3561', 'name': 'Quỹ phát triển khoa học và công nghệ', 'account_type': 'liability'},
 {'code': '3562',
  'name': 'Quỹ phát triển khoa học và công nghệ đã hình thành tài sản cố định',
  'account_type': 'liability'},
 {'code': '357', 'name': 'Quỹ bình ổn giá', 'account_type': 'liability'},
 {'code': '411', 'name': 'Vốn đầu tư của chủ sở hữu', 'account_type': 'equity'},
 {'code': '4111', 'name': 'Vốn góp của chủ sở hữu', 'account_type': 'equity'},
 {'code': '4112', 'name': 'Thặng dư vốn cổ phần', 'account_type': 'equity'},
 {'code': '4113', 'name': 'Quyền chọn chuyển đổi trái phiếu', 'account_type': 'equity'},
 {'code': '4118', 'name': 'Vốn khác', 'account_type': 'equity'},
 {'code': '412', 'name': 'Chênh lệch đánh giá lại tài sản', 'account_type': 'equity'},
 {'code': '413', 'name': 'Chênh lệch tỷ giá hối đoái', 'account_type': 'equity'},
 {'code': '4131',
  'name': 'Chênh lệch tỷ giá do đánh giá lại các khoản mục tiền tệ có gốc ngoại tệ',
  'account_type': 'equity'},
 {'code': '4132',
  'name': 'Chênh lệch tỷ giá hối đoái trong giai đoạn trước hoạt động',
  'account_type': 'equity'},
 {'code': '414', 'name': 'Quỹ đầu tư phát triển', 'account_type': 'equity'},
 {'code': '417', 'name': 'Quỹ hỗ trợ sắp xếp doanh nghiệp', 'account_type': 'equity'},
 {'code': '418', 'name': 'Các quỹ khác thuộc vốn chủ sở hữu', 'account_type': 'equity'},
 {'code': '419', 'name': 'Cổ phiếu quỹ', 'account_type': 'equity'},
 {'code': '421', 'name': 'Lợi nhuận sau thuế chưa phân phối', 'account_type': 'equity'},
 {'code': '4211', 'name': 'Lợi nhuận sau thuế chưa phân phối năm trước', 'account_type': 'equity'},
 {'code': '4212', 'name': 'Lợi nhuận sau thuế chưa phân phối năm nay', 'account_type': 'equity'},
 {'code': '441', 'name': 'Nguồn vốn đầu tư xây dựng cơ bản', 'account_type': 'equity'},
 {'code': '461', 'name': 'Nguồn kinh phí sự nghiệp', 'account_type': 'equity'},
 {'code': '4611', 'name': 'Nguồn kinh phí sự nghiệp năm trước', 'account_type': 'equity'},
 {'code': '4612', 'name': 'Nguồn kinh phí sự nghiệp năm nay', 'account_type': 'equity'},
 {'code': '466', 'name': 'Nguồn kinh phí đã hình thành tài sản cố định', 'account_type': 'equity'},
 {'code': '511', 'name': 'Doanh thu bán hàng và cung cấp dịch vụ', 'account_type': 'revenue'},
 {'code': '5111', 'name': 'Doanh thu bán hàng hóa', 'account_type': 'revenue'},
 {'code': '5112', 'name': 'Doanh thu bán thành phẩm', 'account_type': 'revenue'},
 {'code': '5113', 'name': 'Doanh thu cung cấp dịch vụ', 'account_type': 'revenue'},
 {'code': '5114', 'name': 'Doanh thu trợ cấp, trợ giá', 'account_type': 'revenue'},
 {'code': '5117', 'name': 'Doanh thu kinh doanh bất động sản đầu tư', 'account_type': 'revenue'},
 {'code': '5118', 'name': 'Doanh thu khác', 'account_type': 'revenue'},
 {'code': '515', 'name': 'Doanh thu hoạt động tài chính', 'account_type': 'revenue'},
 {'code': '521', 'name': 'Các khoản giảm trừ doanh thu', 'account_type': 'revenue'},
 {'code': '5211', 'name': 'Chiết khấu thương mại', 'account_type': 'revenue'},
 {'code': '5212', 'name': 'Hàng bán bị trả lại', 'account_type': 'revenue'},
 {'code': '5213', 'name': 'Giảm giá hàng bán', 'account_type': 'revenue'},
 {'code': '611', 'name': 'Mua hàng', 'account_type': 'expense'},
 {'code': '6111', 'name': 'Mua nguyên liệu, vật liệu', 'account_type': 'expense'},
 {'code': '6112', 'name': 'Mua hàng hóa', 'account_type': 'expense'},
 {'code': '621', 'name': 'Chi phí nguyên liệu, vật liệu trực tiếp', 'account_type': 'expense'},
 {'code': '622', 'name': 'Chi phí nhân công trực tiếp', 'account_type': 'expense'},
 {'code': '623', 'name': 'Chi phí sử dụng máy thi công', 'account_type': 'expense'},
 {'code': '6231', 'name': 'Chi phí nhân công sử dụng máy thi công', 'account_type': 'expense'},
 {'code': '6232',
  'name': 'Chi phí nguyên, nhiên, vật liệu sử dụng máy thi công',
  'account_type': 'expense'},
 {'code': '6233',
  'name': 'Chi phí dụng cụ sản xuất sử dụng máy thi công',
  'account_type': 'expense'},
 {'code': '6234', 'name': 'Chi phí khấu hao máy thi công', 'account_type': 'expense'},
 {'code': '6237',
  'name': 'Chi phí dịch vụ mua ngoài sử dụng máy thi công',
  'account_type': 'expense'},
 {'code': '6238', 'name': 'Chi phí bằng tiền khác sử dụng máy thi công', 'account_type': 'expense'},
 {'code': '627', 'name': 'Chi phí sản xuất chung', 'account_type': 'expense'},
 {'code': '6271', 'name': 'Chi phí nhân viên phân xưởng', 'account_type': 'expense'},
 {'code': '6272', 'name': 'Chi phí nguyên, vật liệu', 'account_type': 'expense'},
 {'code': '6273', 'name': 'Chi phí dụng cụ sản xuất', 'account_type': 'expense'},
 {'code': '6274', 'name': 'Chi phí khấu hao tài sản cố định', 'account_type': 'expense'},
 {'code': '6277', 'name': 'Chi phí dịch vụ mua ngoài', 'account_type': 'expense'},
 {'code': '6278', 'name': 'Chi phí bằng tiền khác', 'account_type': 'expense'},
 {'code': '631', 'name': 'Giá thành sản xuất', 'account_type': 'expense'},
 {'code': '632', 'name': 'Giá vốn hàng bán', 'account_type': 'expense'},
 {'code': '635', 'name': 'Chi phí tài chính', 'account_type': 'expense'},
 {'code': '641', 'name': 'Chi phí bán hàng', 'account_type': 'expense'},
 {'code': '6411', 'name': 'Chi phí nhân viên bán hàng', 'account_type': 'expense'},
 {'code': '6412', 'name': 'Chi phí vật liệu, bao bì', 'account_type': 'expense'},
 {'code': '6413', 'name': 'Chi phí dụng cụ, đồ dùng bán hàng', 'account_type': 'expense'},
 {'code': '6414', 'name': 'Chi phí khấu hao tài sản cố định bán hàng', 'account_type': 'expense'},
 {'code': '6415', 'name': 'Chi phí bảo hành', 'account_type': 'expense'},
 {'code': '6417', 'name': 'Chi phí dịch vụ mua ngoài bán hàng', 'account_type': 'expense'},
 {'code': '6418', 'name': 'Chi phí bằng tiền khác bán hàng', 'account_type': 'expense'},
 {'code': '642', 'name': 'Chi phí quản lý doanh nghiệp', 'account_type': 'expense'},
 {'code': '6421', 'name': 'Chi phí nhân viên quản lý', 'account_type': 'expense'},
 {'code': '6422', 'name': 'Chi phí vật liệu quản lý', 'account_type': 'expense'},
 {'code': '6423', 'name': 'Chi phí đồ dùng văn phòng', 'account_type': 'expense'},
 {'code': '6424', 'name': 'Chi phí khấu hao tài sản cố định quản lý', 'account_type': 'expense'},
 {'code': '6425', 'name': 'Thuế, phí và lệ phí', 'account_type': 'expense'},
 {'code': '6426', 'name': 'Chi phí dự phòng', 'account_type': 'expense'},
 {'code': '6427', 'name': 'Chi phí dịch vụ mua ngoài quản lý', 'account_type': 'expense'},
 {'code': '6428', 'name': 'Chi phí bằng tiền khác quản lý', 'account_type': 'expense'},
 {'code': '711', 'name': 'Thu nhập khác', 'account_type': 'revenue'},
 {'code': '811', 'name': 'Chi phí khác', 'account_type': 'expense'},
 {'code': '821', 'name': 'Chi phí thuế thu nhập doanh nghiệp', 'account_type': 'expense'},
 {'code': '8211', 'name': 'Chi phí thuế TNDN hiện hành', 'account_type': 'expense'},
 {'code': '8212', 'name': 'Chi phí thuế TNDN hoãn lại', 'account_type': 'expense'},
 {'code': '911', 'name': 'Xác định kết quả kinh doanh', 'account_type': 'equity'}]
